# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc1', models.TextField(max_length=200)),
                ('doc2', models.TextField(max_length=200)),
            ],
        ),
    ]
